version: 0.2

env:
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /simple-flask-app/docker-credentials/username
    DOCKER_REGISTRY_PASSWORD: /simple-flask-app/docker-credentials/password
    DOCKER_REGISTRY_URL: /simple-flask-app/docker-registry/url

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo "Logging in to Docker registry..."
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login "$DOCKER_REGISTRY_URL" --username "$DOCKER_REGISTRY_USERNAME" --password-stdin
      - echo "Installing Python dependencies..."
      - pip install -r aws-cicd/simple-python-app/requirements.txt
  build:
    commands:
      - echo "Navigating to application directory..."
      - cd aws-cicd/simple-python-app
      - echo "Building Docker image..."
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/sample-python-flask-app:latest" .
      - echo "Pushing Docker image..."
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/sample-python-flask-app:latest"
  post_build:
    commands:
      - echo "Build Successful"
